// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeql2IatD3GHwAXrr3S2EXfNGQBh0vZj8',
    appId: '1:16052237336:web:b2781d85b9f3dc7a84ff6d',
    messagingSenderId: '16052237336',
    projectId: 'fir-services-c1f90',
    authDomain: 'fir-services-c1f90.firebaseapp.com',
    storageBucket: 'fir-services-c1f90.firebasestorage.app',
    measurementId: 'G-L976GLGR57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6BVAKSYBBI124wygENjfT2mWyNf0IsDA',
    appId: '1:16052237336:android:4f06c7386c02f92d84ff6d',
    messagingSenderId: '16052237336',
    projectId: 'fir-services-c1f90',
    storageBucket: 'fir-services-c1f90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFbY6XUPyA9whWYqZjEH5CeRoih3PvUPo',
    appId: '1:16052237336:ios:4195c5ac7c74863184ff6d',
    messagingSenderId: '16052237336',
    projectId: 'fir-services-c1f90',
    storageBucket: 'fir-services-c1f90.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFbY6XUPyA9whWYqZjEH5CeRoih3PvUPo',
    appId: '1:16052237336:ios:4195c5ac7c74863184ff6d',
    messagingSenderId: '16052237336',
    projectId: 'fir-services-c1f90',
    storageBucket: 'fir-services-c1f90.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeql2IatD3GHwAXrr3S2EXfNGQBh0vZj8',
    appId: '1:16052237336:web:3c5544cb9368482084ff6d',
    messagingSenderId: '16052237336',
    projectId: 'fir-services-c1f90',
    authDomain: 'fir-services-c1f90.firebaseapp.com',
    storageBucket: 'fir-services-c1f90.firebasestorage.app',
    measurementId: 'G-GYB8H8Z487',
  );

}